export const dummyTickets = [
  { title: "Login issue on mobile app", description: "Customer is unable to login using correct credentials on Android device." },
  { title: "Payment failed but amount deducted", description: "User reports payment failure message but money was deducted from bank account." },
  { title: "Unable to reset password", description: "Password reset link is not being received on registered email address." },
  { title: "App crashing on checkout", description: "Application crashes when user tries to place order from cart page." },
  { title: "Order not delivered", description: "Customer has not received order even after delivery date has passed." },
  { title: "Refund not processed", description: "Refund was requested 7 days ago but not yet credited." },
  { title: "Account temporarily blocked", description: "User account is showing blocked without any prior notification." },
  { title: "Incorrect billing amount", description: "Invoice shows higher amount than actual product price." },
  { title: "Unable to update profile details", description: "Changes made to profile are not getting saved." },
  { title: "OTP not received", description: "Customer is not receiving OTP for verification." },

  { title: "Subscription not activated", description: "User paid for subscription but premium access not granted." },
  { title: "Coupon code not working", description: "Valid discount coupon shows invalid error during checkout." },
  { title: "Delayed email notifications", description: "System notifications are reaching customer after significant delay." },
  { title: "Product damaged on arrival", description: "Customer received damaged product and requesting replacement." },
  { title: "Wrong item delivered", description: "Order contains different product than what was purchased." },
  { title: "Unable to upload documents", description: "Document upload feature throws error while submitting form." },
  { title: "Live chat not responding", description: "Live chat support is not connecting to any agent." },
  { title: "App loading very slow", description: "Customer reports slow loading time on dashboard screen." },
  { title: "Address change not reflected", description: "Updated shipping address not applied to current order." },
  { title: "Duplicate transaction record", description: "Transaction history shows duplicate payment entry." },

  { title: "Feature request: Dark mode", description: "Customer requesting dark mode support in mobile app." },
  { title: "Cannot download invoice", description: "Download invoice button is not working." },
  { title: "Session timeout too frequent", description: "User gets logged out automatically within short interval." },
  { title: "Error 500 on dashboard", description: "Internal server error appears when accessing dashboard." },
  { title: "Notification settings not saving", description: "Changes in notification preferences are not being saved." },
  { title: "Order tracking not updating", description: "Tracking status remains unchanged even after dispatch." },
  { title: "Search results inaccurate", description: "Search feature shows unrelated products." },
  { title: "Unable to add product to wishlist", description: "Wishlist button does not respond on click." },
  { title: "Profile picture upload fails", description: "Error occurs while uploading new profile picture." },
  { title: "Payment gateway timeout", description: "Payment process times out during transaction." },

  { title: "App not compatible with latest update", description: "After device update, app fails to launch properly." },
  { title: "Email verification link expired", description: "Verification link shows expired immediately after clicking." },
  { title: "Incorrect reward points balance", description: "Reward points shown are less than expected." },
  { title: "Unable to cancel order", description: "Cancel order option disabled before shipping." },
  { title: "Push notifications not working", description: "Customer not receiving push notifications on device." },
  { title: "Language preference not applied", description: "Selected language resets to default after refresh." },
  { title: "Payment receipt not generated", description: "System failed to generate receipt after successful payment." },
  { title: "Two-factor authentication error", description: "2FA verification fails even with correct code." },
  { title: "Data sync issue between devices", description: "User data not syncing across multiple logged-in devices." },
  { title: "Incorrect tax calculation", description: "Tax amount calculated incorrectly during checkout." },

  { title: "App freezes on startup", description: "Application gets stuck on splash screen." },
  { title: "Unable to apply referral code", description: "Referral code shows invalid despite meeting criteria." },
  { title: "Order history missing", description: "Previous orders are not visible in account section." },
  { title: "Account deleted without request", description: "Customer claims account was removed without consent." },
  { title: "Unable to update payment method", description: "System prevents adding new debit card." },
  { title: "Chat messages not sending", description: "Messages fail to send in support chat window." },
  { title: "Discount not applied at checkout", description: "Promotional discount missing in final billing." },
  { title: "App logout issue", description: "User remains logged in even after clicking logout." },
  { title: "Delivery partner unresponsive", description: "Customer unable to contact assigned delivery partner." },
  { title: "App showing blank screen", description: "White blank screen appears after login." }
];
